

export const WEB_EVENTS = {
    OPT_SENT: 'otp_sent',
    LOGGED_IN: 'logged_in',
    BUY_PLAN_CLICKED: 'BUY_PLAN_CLICKED',
    PLAN_PURCHASED_SUCCESS: 'PLAN_PURCHASED_SUCCESS',
    PLAN_PURCHASED_FAILED: 'PLAN_PURCHASED_FAILED',
    ACCOUNT_SUSPENDED: 'account_suspended',
    OPENED_MRKETING_PAGE: 'OPENED_MRKETING_PAGE',
    OPENED_APP_PAGE: 'OPENED_APP_PAGE',
}