

export const BG_FETCH_USER_DETAILS = 'BG_FETCH_USER_DETAILS';
export const BG_GET_USER_DETAILS = 'BG_GET_USER_DETAILS';
export const BG_FETCH_USER_ORDERS = 'BG_FETCH_USER_ORDERS';
export const BG_UPDATE_AVAILABLE_CREDITS = 'BG_UPDATE_AVAILABLE_CREDITS';
export const BG_TRACK_EVENT = 'BG_TRACK_EVENT';
export const BG_GET_TOKEN = 'BG_GET_TOKEN';
export const BG_SET_TOKEN = 'BG_SET_TOKEN';
export const BG_CLEAR_EVERYTHING= 'BG_CLEAR_EVERYTHING';
export const BG_LOGOUT_USER = 'BG_LOGOUT_USER';
export const BG_BROADCAST= 'BG_BROADCAST';



export const BroadcastMessages = {
    REFRESH_USER_DETAILS: 'REFRESH_USER_DETAILS',
    USER_LOGGED_OUT: 'USER_LOGGED_OUT'
}