

export const BG_FETCH_USER_DETAILS = 'BG_FETCH_USER_DETAILS';
export const BG_GET_USER_DETAILS = 'BG_GET_USER_DETAILS';
export const BG_FETCH_USER_ORDERS = 'BG_FETCH_USER_ORDERS';
export const BG_UPDATE_AVAILABLE_CREDITS = 'BG_UPDATE_AVAILABLE_CREDITS';