

export const CreditBgActions = {
    BG_GET_AVAILABLE_CREDITS: 'BG_GET_AVAILABLE_CREDITS',
    BG_UPDATE_AVAILABLE_CREDITS: 'BG_UPDATE_AVAILABLE_CREDITS',
    BG_GET_TOTAL_CREDITS: 'BG_GET_TOTAL_CREDITS',
    BG_GET_CREDITS_DATA: 'BG_GET_CREDITS_DATA',
    BG_FETCH_CREDITS_DATA: 'BG_FETCH_CREDITS_DATA',
}
