
export const BG_GET_AI_RESPONSE = 'BG_GET_AI_RESPONSE';
export const BG_OPEN_LOGIN_PAGE= 'BG_OPEN_LOGIN_PAGE';
export const BG_GET_USER_DETAILS = 'BG_GET_USER_DETAILS';
export const BG_FETCH_USER_DETAILS = 'BG_FETCH_USER_DETAILS';
export const BG_CLEAR_USER_DETAILS = 'BG_CLEAR_USER_DETAILS';
export const BG_TRACK_EVENT = 'BG_TRACK_EVENT';


export const BroadcastMessages = {
    REFRESH_USER_DETAILS: 'REFRESH_USER_DETAILS',
    USER_LOGGED_OUT: 'USER_LOGGED_OUT'
}