
export const BG_GET_AI_RESPONSE = 'BG_GET_AI_RESPONSE';
export const BG_OPEN_LOGIN_PAGE= 'BG_OPEN_LOGIN_PAGE';
export const BG_GET_USER_DETAILS = 'BG_GET_USER_DETAILS';
export const BG_CLEAR_USER_DETAILS = 'BG_CLEAR_USER_DETAILS';
export const BG_TRACK_EVENT = 'BG_TRACK_EVENT';