
export const Messages = {
    BG_GET_AI_RESPONSE: 'BG_GET_AI_RESPONSE',
    BG_GET_AVAILABLE_CREDITS: 'BG_GET_AVAILABLE_CREDITS',
    BG_UPDATE_AVAILABLE_CREDITS: 'BG_UPDATE_AVAILABLE_CREDITS',
    BG_GET_TOTAL_CREDITS: 'BG_GET_TOTAL_CREDITS',
    BG_GET_CREDITS_DATA: 'BG_GET_CREDITS_DATA',
    BG_FETCH_CREDITS_DATA: 'BG_FETCH_CREDITS_DATA',
    BG_FETCH_USER_DETAILS: 'BG_FETCH_USER_DETAILS',
    BG_GET_USER_DETAILS: 'BG_GET_USER_DETAILS',
    BG_CLEAR_USER_DETAILS: 'BG_CLEAR_USER_DETAILS',
    BG_OPEN_LOGIN_PAGE : 'BG_OPEN_LOGIN_PAGE',
    BG_FETCH_USER_ORDERS : 'BG_FETCH_USER_ORDERS',
    BG_TRACK_EVENT: 'BG_TRACK_EVENT',
    BG_SET_TOKEN: 'BG_SET_TOKEN',
    BG_GET_TOKEN: 'BG_GET_TOKEN',
    BG_LOGOUT_USER: 'BG_LOGOUT_USER',
    BG_BROADCAST:'BG_BROADCAST',
}

export const BroadcastMessages = {
    USER_LOGGED_OUT: 'USER_LOGGED_OUT'
}

export const DEFAULT_CREDITS_PER_DAY = 25;

export const Routes = {
    AI: '/ai',
    credits: '/credits',
    userDetails: '/user/details',
    ordersList: '/orders/list'
}

export const Events = {
    EXTENSION_INSTALLED: "extension_installed",
    EXTENSION_UNINSTALLED: "extension_uninstalled",
};
export const AI_STREAM_RESPONSE_KEY = 'AI_RESPONSE'
export const AI_STREAM_CONNECT_KEY = 'AI_MESSAGE'