
export const Messages = {
    BG_GET_AI_RESPONSE: 'BG_GET_AI_RESPONSE',
    BG_GET_AVAILABLE_CREDITS: 'BG_GET_AVAILABLE_CREDITS',
    BG_UPDATE_AVAILABLE_CREDITS: 'BG_UPDATE_AVAILABLE_CREDITS',
    BG_GET_TOTAL_CREDITS: 'BG_GET_TOTAL_CREDITS',
    BG_GET_CREDITS_DATA: 'BG_GET_CREDITS_DATA',
    BG_FETCH_CREDITS_DATA: 'BG_FETCH_CREDITS_DATA',
    BG_FETCH_USER_DETAILS: 'BG_FETCH_USER_DETAILS',
    BG_GET_USER_DETAILS: 'BG_GET_USER_DETAILS',

}

export const DEFAULT_CREDITS_PER_DAY = 25;

export const API_URL = 'http://localhost:8000';

export const Routes = {
    AI: '/ai',
    credits: '/credits',
    userDetails: '/user/details'
}